routes:
  "1":
    # 第一个点是中间的过道2.50, 2.03
    - {x: 2.50, y: 2.03, yaw: 1.57}
    # 岔路2.48, 3.11
    - {x: 2.48, y: 3.11, yaw: 0.0}
    # 右边弯道4.20, 3.20
    - {x: 4.20, y: 3.20, yaw: 1.57}
    # 最上方2.50, 4.37
    - {x: 2.50, y: 4.37, yaw: -3.14}
    # 左边弯道0.79, 3.19
    - {x: 0.79, y: 3.19, yaw: 0.0}
    # 回到过道
    - {x: 2.50, y: 2.03, yaw: -1.57}

  "2":
    # 实例，第一个点是中间的过道2.50, 2.03
    - {x: 2.50, y: 2.03, yaw: 1.57}
    # 岔路2.48, 3.11
    - {x: 2.48, y: 3.11, yaw: -3.14}
    # 左边弯道0.79, 3.19
    - {x: 0.79, y: 3.19, yaw: 1.57}
    # 最上方2.50, 4.37
    - {x: 2.50, y: 4.37, yaw: 0.0}
    # 右边弯道4.20, 3.20
    - {x: 4.20, y: 3.20, yaw: 3.14}
    # 回到过道
    - {x: 2.50, y: 2.03, yaw: -1.57}